# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Transit Equity
tagline:          ''
description:      'A 2024 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://uwescience.github.io"
baseurl:          "/DSSG2024_transit_equity"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/DSSG2024_transit_equity/
