# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Investigating Transit Equity Through ORCA Fare Card Analysis
tagline:          ''
description:      'Data Science for Social Good 2024, University of Washington' 
url:              "https://uwescience.github.io"
baseurl:          "/DSSG2024_transit_equity"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/DSSG2024_transit_equity/
